# AUTO-GENERATED by integration/scripts/gen_self_replicate_fixtures.sh
# from integration/scripts/self_replicate_modules.sh — do not edit
# directly; update the manifest and rerun the generator instead.
#
# Self-replicate step 1: build /sd/full.s referencing /sd/dx.img
# (the kernel-dumped disk-extra.img). The .incbin in mtfs_wrap_x.s
# points at /sd/dx.img with the host's exact disk-extra.img size.
#
# Module order matches compile-gen2.sh's emit order for kernel_pico2.tc:
#   prelude = raw + platform_pico2.s + trap_common.s + runtime.s
#   in_0  = kc.s (kernel/src/kernel_common.tc)
#   in_1  = pp.s (kernel/platform/pico2/platform_pico2.tc)
#   in_2  = bf.s (kernel/platform/pico2/block_flash.tc)
#   in_3  = bs.s (kernel/platform/pico2/block_sd.tc)
#   in_4  = ff.s (kernel/src/fatfs.tc)
#   in_5  = mf.s (kernel/src/mtfs.tc)
#   in_6  = tf.s (kernel/src/tmpfs.tc)
#   in_7  = pf.s (kernel/src/procfs.tc)
#   in_8  = rt.s (kernel/src/rtc.tc)
#   in_9  = df.s (kernel/src/devfs.tc)
#   in_10 = vf.s (kernel/src/vfs.tc)
#   in_11 = ld.s (kernel/src/loader.tc)
#   in_12 = r3.s (kernel/platform/pico2/rtc_ds3231.tc)
#   in_13 = di.s (kernel/platform/pico2/display_ili9488.tc)
#   in_14 = km.s (kernel/platform/pico2/keyboard_matrix.tc)
#   in_15 = tp.s (kernel/platform/pico2/touch_xpt2046.tc)
#   in_16 = kp.s (kernel/src/kernel_pico2.tc)
#   tail    = crt0_pico2_data.s + wrap.s
cat /src/raw.s /src/platform_pico2.s /src/trap_common.s /sd/runtime.s /sd/kc.s /sd/pp.s /sd/bf.s /sd/bs.s /sd/ff.s /sd/mf.s /sd/tf.s /sd/pf.s /sd/rt.s /sd/df.s /sd/vf.s /sd/ld.s /sd/r3.s /sd/di.s /sd/km.s /sd/tp.s /sd/kp.s /src/crt0_pico2_data.s /sd/wrap.s > /sd/full.s
md5sum /sd/full.s
echo SELF_STEP1_DONE
