# AUTO-GENERATED by integration/scripts/gen_self_replicate_fixtures.sh
# from integration/scripts/self_replicate_modules.sh — do not edit
# directly; update the manifest and rerun the generator instead.
#
# Compile kernel modules with imports. Reuses leaf .th files staged
# by pico2_compile_kern.sh — that fixture must run before this one.
# Also depends on /sd/pp.th from pico2_compile_platform.sh.
# ff: imports kc
parse < /src/fatfs.tc > /sd/ff.ast
sigscan < /sd/ff.ast > /sd/ff.th
tcheck --exth /sd/kc.th --tgth /sd/ff.th --tgt /sd/ff.ast --out /sd/ff.tast
codegen < /sd/ff.tast > /sd/ff.bc
bc2asm < /sd/ff.bc > /sd/ff.s
md5sum /sd/ff.s
# mf: imports kc
parse < /src/mtfs.tc > /sd/mf.ast
sigscan < /sd/mf.ast > /sd/mf.th
tcheck --exth /sd/kc.th --tgth /sd/mf.th --tgt /sd/mf.ast --out /sd/mf.tast
codegen < /sd/mf.tast > /sd/mf.bc
bc2asm < /sd/mf.bc > /sd/mf.s
md5sum /sd/mf.s
# pf: imports kc
parse < /src/procfs.tc > /sd/pf.ast
sigscan < /sd/pf.ast > /sd/pf.th
tcheck --exth /sd/kc.th --tgth /sd/pf.th --tgt /sd/pf.ast --out /sd/pf.tast
codegen < /sd/pf.tast > /sd/pf.bc
bc2asm < /sd/pf.bc > /sd/pf.s
md5sum /sd/pf.s
# df: imports kc rt
parse < /src/devfs.tc > /sd/df.ast
sigscan < /sd/df.ast > /sd/df.th
tcheck --exth /sd/kc.th --exth /sd/rt.th --tgth /sd/df.th --tgt /sd/df.ast --out /sd/df.tast
codegen < /sd/df.tast > /sd/df.bc
bc2asm < /sd/df.bc > /sd/df.s
md5sum /sd/df.s
# vf: imports mf tf pf df ff kc
parse < /src/vfs.tc > /sd/vf.ast
sigscan < /sd/vf.ast > /sd/vf.th
tcheck --exth /sd/mf.th --exth /sd/tf.th --exth /sd/pf.th --exth /sd/df.th --exth /sd/ff.th --exth /sd/kc.th --tgth /sd/vf.th --tgt /sd/vf.ast --out /sd/vf.tast
codegen < /sd/vf.tast > /sd/vf.bc
bc2asm < /sd/vf.bc > /sd/vf.s
md5sum /sd/vf.s
# ld: imports vf kc
parse < /src/loader.tc > /sd/ld.ast
sigscan < /sd/ld.ast > /sd/ld.th
tcheck --exth /sd/vf.th --exth /sd/kc.th --tgth /sd/ld.th --tgt /sd/ld.ast --out /sd/ld.tast
codegen < /sd/ld.tast > /sd/ld.bc
bc2asm < /sd/ld.bc > /sd/ld.s
md5sum /sd/ld.s
# r3: imports rt
parse < /src/rtc_ds3231.tc > /sd/r3.ast
sigscan < /sd/r3.ast > /sd/r3.th
tcheck --exth /sd/rt.th --tgth /sd/r3.th --tgt /sd/r3.ast --out /sd/r3.tast
codegen < /sd/r3.tast > /sd/r3.bc
bc2asm < /sd/r3.bc > /sd/r3.s
md5sum /sd/r3.s
# kp: imports kc pp bf bs ff mf vf ld r3 di km
parse < /src/kernel_pico2.tc > /sd/kp.ast
sigscan < /sd/kp.ast > /sd/kp.th
tcheck --exth /sd/kc.th --exth /sd/pp.th --exth /sd/bf.th --exth /sd/bs.th --exth /sd/ff.th --exth /sd/mf.th --exth /sd/vf.th --exth /sd/ld.th --exth /sd/r3.th --exth /sd/di.th --exth /sd/km.th --tgth /sd/kp.th --tgt /sd/kp.ast --out /sd/kp.tast
codegen < /sd/kp.tast > /sd/kp.bc
bc2asm < /sd/kp.bc > /sd/kp.s
md5sum /sd/kp.s
echo COMPILE_KERN2_DONE
