# AUTO-GENERATED by integration/scripts/gen_self_replicate_fixtures.sh
# from integration/scripts/self_replicate_modules.sh — do not edit
# directly; update the manifest and rerun the generator instead.
#
# Compile each kernel/*.tc on pico2 → .s, md5 each. We're after
# byte-exactness against host build/intermediate/gen2/kernel_pico2/*.s.
# This file holds modules with NO imports (leaves); modules with
# imports are in pico2_compile_kern2.sh.
parse < /src/kernel_common.tc > /sd/kc.ast
sigscan < /sd/kc.ast > /sd/kc.th
tcheck --tgth /sd/kc.th --tgt /sd/kc.ast --out /sd/kc.tast
codegen < /sd/kc.tast > /sd/kc.bc
bc2asm < /sd/kc.bc > /sd/kc.s
md5sum /sd/kc.s
parse < /src/block_flash.tc > /sd/bf.ast
sigscan < /sd/bf.ast > /sd/bf.th
tcheck --tgth /sd/bf.th --tgt /sd/bf.ast --out /sd/bf.tast
codegen < /sd/bf.tast > /sd/bf.bc
bc2asm < /sd/bf.bc > /sd/bf.s
md5sum /sd/bf.s
parse < /src/block_sd.tc > /sd/bs.ast
sigscan < /sd/bs.ast > /sd/bs.th
tcheck --tgth /sd/bs.th --tgt /sd/bs.ast --out /sd/bs.tast
codegen < /sd/bs.tast > /sd/bs.bc
bc2asm < /sd/bs.bc > /sd/bs.s
md5sum /sd/bs.s
parse < /src/tmpfs.tc > /sd/tf.ast
sigscan < /sd/tf.ast > /sd/tf.th
tcheck --tgth /sd/tf.th --tgt /sd/tf.ast --out /sd/tf.tast
codegen < /sd/tf.tast > /sd/tf.bc
bc2asm < /sd/tf.bc > /sd/tf.s
md5sum /sd/tf.s
parse < /src/rtc.tc > /sd/rt.ast
sigscan < /sd/rt.ast > /sd/rt.th
tcheck --tgth /sd/rt.th --tgt /sd/rt.ast --out /sd/rt.tast
codegen < /sd/rt.tast > /sd/rt.bc
bc2asm < /sd/rt.bc > /sd/rt.s
md5sum /sd/rt.s
parse < /src/display_ili9488.tc > /sd/di.ast
sigscan < /sd/di.ast > /sd/di.th
tcheck --tgth /sd/di.th --tgt /sd/di.ast --out /sd/di.tast
codegen < /sd/di.tast > /sd/di.bc
bc2asm < /sd/di.bc > /sd/di.s
md5sum /sd/di.s
parse < /src/keyboard_matrix.tc > /sd/km.ast
sigscan < /sd/km.ast > /sd/km.th
tcheck --tgth /sd/km.th --tgt /sd/km.ast --out /sd/km.tast
codegen < /sd/km.tast > /sd/km.bc
bc2asm < /sd/km.bc > /sd/km.s
md5sum /sd/km.s
parse < /src/touch_xpt2046.tc > /sd/tp.ast
sigscan < /sd/tp.ast > /sd/tp.th
tcheck --tgth /sd/tp.th --tgt /sd/tp.ast --out /sd/tp.tast
codegen < /sd/tp.tast > /sd/tp.bc
bc2asm < /sd/tp.bc > /sd/tp.s
md5sum /sd/tp.s
echo COMPILE_KERN_LEAVES_DONE
