#!/bin/bash
# gen_self_replicate_fixtures.sh — generate the device-side
# self_replicate fixtures from the kernel module manifest. Run any
# time kernel_pico2.tc's import set changes.
#
# Manifest:    integration/scripts/self_replicate_modules.sh
# Generates:   integration/fixtures/pico2_self_step1.sh
#              integration/fixtures/pico2_self_step2.sh
#              integration/fixtures/pico2_compile_kern.sh
#              integration/fixtures/pico2_compile_kern2.sh
#
# Usage:
#   bash integration/scripts/gen_self_replicate_fixtures.sh        # regenerate
#   bash integration/scripts/gen_self_replicate_fixtures.sh --check # diff-only
#
# --check exits 0 if the on-disk fixtures already match what this
# script would produce — used by Make / CI to catch drift between
# the manifest and the checked-in files.

set -e

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_DIR="$ROOT_DIR/integration/scripts"
OUT_DIR="$ROOT_DIR/integration/fixtures"

# shellcheck source=self_replicate_modules.sh
source "$SCRIPT_DIR/self_replicate_modules.sh"

# Guard: the manifest must cover kernel_pico2.tc's full import closure.
# Twice now a new kernel module was added without updating the manifest
# (K20: rtc/devfs/..., 2026-07-06: touch_xpt2046), silently shifting
# compile-gen2's INPUT_NAMES mapping and breaking byte-exactness.
_closure=$("$ROOT_DIR/compiler/scripts/collect_imports.sh"     "$ROOT_DIR/kernel/src/kernel_pico2.tc"     | sed "s|^$ROOT_DIR/||; s|kernel/src/\.\./|kernel/|" | sort)
_manifest=$(for _e in "${KERNEL_MODULES[@]}"; do echo "${_e##*|}"; done | sort)
if [ "$_closure" != "$_manifest" ]; then
    echo "ERROR: self_replicate_modules.sh manifest != kernel_pico2.tc import closure" >&2
    echo "--- import closure vs manifest ---" >&2
    diff <(echo "$_closure") <(echo "$_manifest") >&2 || true
    exit 1
fi

MODE="${1:-write}"
case "$MODE" in
    --check) MODE=check ;;
    "")      MODE=write ;;
    *)       MODE=write ;;
esac

HDR="# AUTO-GENERATED by integration/scripts/gen_self_replicate_fixtures.sh
# from integration/scripts/self_replicate_modules.sh — do not edit
# directly; update the manifest and rerun the generator instead."

# -- step1.sh ---------------------------------------------------------
gen_step1() {
    cat <<EOF
$HDR
#
# Self-replicate step 1: build /sd/full.s referencing /sd/dx.img
# (the kernel-dumped disk-extra.img). The .incbin in mtfs_wrap_x.s
# points at /sd/dx.img with the host's exact disk-extra.img size.
#
# Module order matches compile-gen2.sh's emit order for kernel_pico2.tc:
#   prelude = raw + platform_pico2.s + trap_common.s + runtime.s
EOF
    local i=0 short
    for short in $(module_short_names); do
        printf '#   in_%-2d = %s.s (%s)\n' "$i" "$short" "$(module_path_by_short "$short")"
        i=$((i+1))
    done
    cat <<EOF
#   tail    = crt0_pico2_data.s + wrap.s
EOF
    # The actual cat command
    printf 'cat /src/raw.s /src/platform_pico2.s /src/trap_common.s /sd/runtime.s'
    for short in $(module_short_names); do
        printf ' /sd/%s.s' "$short"
    done
    printf ' /src/crt0_pico2_data.s /sd/wrap.s > /sd/full.s\n'
    cat <<'EOF'
md5sum /sd/full.s
echo SELF_STEP1_DONE
EOF
}

# -- step2.sh ---------------------------------------------------------
gen_step2() {
    cat <<EOF
$HDR
#
# Self-replicate step 2 — per-file pre-encode + link.
#
# Same pipeline shape compile-gen2.sh uses on the host: pre-encode
# each input with asm_pass1 (small task arena footprint) then merge
# with asm_pass2.
#
# Order MUST match host compile-gen2.sh emit order:
#   prelude = ; raw + platform_pico2.s + trap_common.s + runtime.s
EOF
    local i=0 short
    for short in $(module_short_names); do
        printf '#   in_%-2d = %s.s (%s)\n' "$i" "$short" "$(module_path_by_short "$short")"
        i=$((i+1))
    done
    cat <<'EOF'
#   tail  = crt0_pico2_data.s + wrap.s
#
# Per-file approach keeps each asm_pass1 invocation at ~50-150 KB
# peak on its own small input. The task exits before the next runs,
# so the kernel arena's 504 KB only ever hosts one asm_pass1 task
# at a time.

EOF
    local emit_pass1
    emit_pass1() {
        local src="$1" stem="$2"
        printf 'asm_pass1 %s --idx-out /sd/%s.idx --text-bin /sd/%s.tx --rodata-bin /sd/%s.ro --data-bin /sd/%s.dt --reloc-out /sd/%s.rl\n' \
            "$src" "$stem" "$stem" "$stem" "$stem" "$stem"
    }
    emit_pass1 "/src/raw.s"             "raw"
    emit_pass1 "/src/platform_pico2.s"  "platform"
    emit_pass1 "/src/trap_common.s"     "trap"
    emit_pass1 "/sd/runtime.s"          "runtime"
    for short in $(module_short_names); do
        emit_pass1 "/sd/$short.s" "$short"
    done
    emit_pass1 "/src/crt0_pico2_data.s" "cd"
    emit_pass1 "/sd/wrap.s"             "wrap"
    # asm_pass2 link line
    printf 'asm_pass2'
    for tag in raw platform trap runtime $(module_short_names) cd wrap; do
        printf ' --add /sd/%s.idx' "$tag"
    done
    printf ' --lab-out /sd/full.lab\n'
    cat <<'EOF'
md5sum /sd/full.lab
echo SELF_STEP2_DONE
EOF
}

# -- compile_kern{,2}.sh ----------------------------------------------
# Modules with NO imports go to kern.sh (leaves, runnable first).
# Modules with imports go to kern2.sh (need prior .th files).
gen_compile_kern() {
    local target_no_imports="$1" target_with_imports="$2"
    {
        cat <<EOF
$HDR
#
# Compile each kernel/*.tc on pico2 → .s, md5 each. We're after
# byte-exactness against host build/intermediate/gen2/kernel_pico2/*.s.
# This file holds modules with NO imports (leaves); modules with
# imports are in pico2_compile_kern2.sh.
EOF
    } > "$target_no_imports"
    {
        cat <<EOF
$HDR
#
# Compile kernel modules with imports. Reuses leaf .th files staged
# by pico2_compile_kern.sh — that fixture must run before this one.
# Also depends on /sd/pp.th from pico2_compile_platform.sh.
EOF
    } > "$target_with_imports"

    local short path imports basename target tcheck_args
    for short in $(module_short_names); do
        path=$(module_path_by_short "$short")
        basename="${path##*/}"
        imports=$(module_direct_imports "$short")
        tcheck_args=""
        local i
        for i in $imports; do
            tcheck_args="$tcheck_args --exth /sd/$i.th"
        done
        if [ -z "$imports" ]; then
            target="$target_no_imports"
        else
            target="$target_with_imports"
        fi
        # platform_pico2 (pp) lives in a dedicated fixture for
        # historical reasons (used by self_replicate even when
        # REFRESH_KERN_MODS is off). Skip it here.
        if [ "$short" = "pp" ]; then continue; fi
        {
            if [ -n "$imports" ]; then
                printf '# %s: imports %s\n' "$short" "$imports"
            fi
            printf 'parse < /src/%s > /sd/%s.ast\n' "$basename" "$short"
            printf 'sigscan < /sd/%s.ast > /sd/%s.th\n' "$short" "$short"
            printf 'tcheck%s --tgth /sd/%s.th --tgt /sd/%s.ast --out /sd/%s.tast\n' \
                "$tcheck_args" "$short" "$short" "$short"
            printf 'codegen < /sd/%s.tast > /sd/%s.bc\n' "$short" "$short"
            printf 'bc2asm < /sd/%s.bc > /sd/%s.s\n' "$short" "$short"
            printf 'md5sum /sd/%s.s\n' "$short"
        } >> "$target"
    done
    echo 'echo COMPILE_KERN_LEAVES_DONE' >> "$target_no_imports"
    echo 'echo COMPILE_KERN2_DONE' >> "$target_with_imports"
}

# --- driver ----------------------------------------------------------
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

gen_step1                                  > "$TMP/pico2_self_step1.sh"
gen_step2                                  > "$TMP/pico2_self_step2.sh"
gen_compile_kern "$TMP/pico2_compile_kern.sh" "$TMP/pico2_compile_kern2.sh"

status=0
for f in pico2_self_step1.sh pico2_self_step2.sh \
         pico2_compile_kern.sh pico2_compile_kern2.sh; do
    if [ "$MODE" = "check" ]; then
        if ! diff -q "$OUT_DIR/$f" "$TMP/$f" >/dev/null 2>&1; then
            echo "drift: $f" >&2
            diff -u "$OUT_DIR/$f" "$TMP/$f" >&2 || true
            status=1
        fi
    else
        cp "$TMP/$f" "$OUT_DIR/$f"
    fi
done

if [ "$MODE" = "check" ]; then
    if [ $status -ne 0 ]; then
        echo "Run 'bash integration/scripts/gen_self_replicate_fixtures.sh' to regenerate." >&2
        exit 1
    fi
    echo "OK: fixtures match manifest"
fi
